-- MySQL Script generated by MySQL Workbench
-- Mon May  6 13:50:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema livrariadb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS livrariadb
-- -----------------------------------------------------
-- Schema livrariadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livrariadb` DEFAULT CHARACTER SET latin1 ;
USE `livrariadb` ;

-- -----------------------------------------------------
-- Table `livrariadb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`user` (
  `iduser` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`avaliacao` (
  `idavaliacao` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `user_iduser` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_avaliacao_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariadb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`estado` (
  `idEstado` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`cidade` (
  `idCidade` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `Estado_idEstado` INT(11) NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado_idx` (`Estado_idEstado` ASC) ,
  CONSTRAINT `fk_Cidade_Estado`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `livrariadb`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`comentarios` (
  `idcomentarios` INT(11) NOT NULL AUTO_INCREMENT,
  `texto` TEXT NULL DEFAULT NULL,
  `user_iduser` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_comentarios_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariadb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`endereco` (
  `idEndereco` INT(11) NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `Cidade_idCidade` INT(11) NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_Cidade1_idx` (`Cidade_idCidade` ASC) ,
  CONSTRAINT `fk_Endereco_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `livrariadb`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`imagens` (
  `idimagens` INT(11) NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(100) NULL DEFAULT NULL,
  `mime` VARCHAR(45) NULL,
  `path` VARCHAR(50) NULL,
  `size` INT NULL,
  `timestamps` TIMESTAMP NULL,
  PRIMARY KEY (`idimagens`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`livro` (
  `idlivro` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `ano` DATE NULL DEFAULT NULL,
  `peso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idlivro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`pessoafisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`pessoafisica` (
  `idpessoaFisica` VARCHAR(13) NOT NULL,
  `Endereco_idEndereco` INT(11) NOT NULL,
  `user_iduser` INT(10) UNSIGNED NOT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `rg` VARCHAR(45) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `imagens_idimagens` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idpessoaFisica`),
  INDEX `fk_pessoaFisica_Endereco1_idx` (`Endereco_idEndereco` ASC) ,
  INDEX `fk_pessoaFisica_user1_idx` (`user_iduser` ASC) ,
  INDEX `fk_pessoaFisica_imagens1_idx` (`imagens_idimagens` ASC) ,
  CONSTRAINT `fk_pessoaFisica_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `livrariadb`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaFisica_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `livrariadb`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaFisica_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariadb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`post` (
  `idpost` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `conteudo` TEXT NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `datapostagem` DATETIME NULL DEFAULT NULL,
  `categoria_idcategoria1` INT(11) NOT NULL,
  PRIMARY KEY (`idpost`, `categoria_idcategoria1`),
  INDEX `fk_post_categoria1_idx1` (`categoria_idcategoria1` ASC) ,
  CONSTRAINT `fk_post_categoria1`
    FOREIGN KEY (`categoria_idcategoria1`)
    REFERENCES `livrariadb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`post_has_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`post_has_avaliacao` (
  `post_idpost` INT(11) NOT NULL,
  `avaliacao_idavaliacao` INT(11) NOT NULL,
  `iduser` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`post_idpost`, `avaliacao_idavaliacao`, `iduser`),
  INDEX `fk_post_has_avaliacao1_idx` (`avaliacao_idavaliacao` ASC, `iduser` ASC) ,
  INDEX `fk_post_has_avaliacao_post1_idx` (`post_idpost` ASC) ,
  CONSTRAINT `fk_post_has_avaliacao_avaliacao1`
    FOREIGN KEY (`avaliacao_idavaliacao`)
    REFERENCES `livrariadb`.`avaliacao` (`idavaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_avaliacao_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariadb`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`post_has_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`post_has_comentarios` (
  `post_idpost` INT(11) NOT NULL,
  `comentarios_idcomentarios` INT(11) NOT NULL,
  `comentarios_user_iduser` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`post_idpost`, `comentarios_idcomentarios`, `comentarios_user_iduser`),
  INDEX `fk_post_has_comentarios_comentarios1_idx` (`comentarios_idcomentarios` ASC, `comentarios_user_iduser` ASC) ,
  INDEX `fk_post_has_comentarios_post1_idx` (`post_idpost` ASC) ,
  CONSTRAINT `fk_post_has_comentarios_comentarios1`
    FOREIGN KEY (`comentarios_idcomentarios`)
    REFERENCES `livrariadb`.`comentarios` (`idcomentarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_comentarios_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariadb`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`post_has_imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`post_has_imagens` (
  `post_idpost` INT(11) NOT NULL,
  `post_categoria_idcategoria` INT(11) NOT NULL,
  `imagens_idimagens` INT(11) NOT NULL,
  PRIMARY KEY (`post_idpost`, `post_categoria_idcategoria`, `imagens_idimagens`),
  INDEX `fk_post_has_imagens_imagens1_idx` (`imagens_idimagens` ASC) ,
  INDEX `fk_post_has_imagens_post1_idx` (`post_idpost` ASC, `post_categoria_idcategoria` ASC) ,
  CONSTRAINT `fk_post_has_imagens_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariadb`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_imagens_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `livrariadb`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`user_has_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`user_has_post` (
  `user_iduser` INT(10) UNSIGNED NOT NULL,
  `post_idpost` INT(11) NOT NULL,
  PRIMARY KEY (`user_iduser`, `post_idpost`),
  INDEX `fk_user_has_post_post1_idx` (`post_idpost` ASC) ,
  INDEX `fk_user_has_post_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_user_has_post_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariadb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_post_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariadb`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`user_has_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`user_has_livro` (
  `user_iduser` INT(10) UNSIGNED NOT NULL,
  `livro_idlivro` INT(11) NOT NULL,
  PRIMARY KEY (`user_iduser`, `livro_idlivro`),
  INDEX `fk_user_has_livro_livro1_idx` (`livro_idlivro` ASC) ,
  INDEX `fk_user_has_livro_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_user_has_livro_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariadb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_livro_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `livrariadb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `nCartao` VARCHAR(45) NULL,
  `vcc` VARCHAR(3) NULL,
  `formaPagamento` VARCHAR(45) NULL,
  `dataValidade` DATE NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariadb`.`pessoafisica_has_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`pessoafisica_has_pagamento` (
  `pessoafisica_idpessoaFisica` VARCHAR(13) NOT NULL,
  `pagamento_idpagamento` INT NOT NULL,
  PRIMARY KEY (`pessoafisica_idpessoaFisica`, `pagamento_idpagamento`),
  INDEX `fk_pessoafisica_has_pagamento_pagamento1_idx` (`pagamento_idpagamento` ASC) ,
  INDEX `fk_pessoafisica_has_pagamento_pessoafisica1_idx` (`pessoafisica_idpessoaFisica` ASC) ,
  CONSTRAINT `fk_pessoafisica_has_pagamento_pessoafisica1`
    FOREIGN KEY (`pessoafisica_idpessoaFisica`)
    REFERENCES `livrariadb`.`pessoafisica` (`idpessoaFisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoafisica_has_pagamento_pagamento1`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `livrariadb`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `livrariadb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NULL,
  `data` TIMESTAMP NULL,
  `livro_idlivro` INT(11) NOT NULL,
  `pagamento_idpagamento` INT NOT NULL,
  PRIMARY KEY (`idcompra`, `livro_idlivro`, `pagamento_idpagamento`),
  INDEX `fk_compra_livro1_idx` (`livro_idlivro` ASC) ,
  INDEX `fk_compra_pagamento1_idx` (`pagamento_idpagamento` ASC) ,
  CONSTRAINT `fk_compra_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `livrariadb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_pagamento1`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `livrariadb`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariadb`.`user_has_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariadb`.`user_has_compra` (
  `user_iduser` INT(10) UNSIGNED NOT NULL,
  `compra_idcompra` INT NOT NULL,
  `compra_livro_idlivro` INT(11) NOT NULL,
  PRIMARY KEY (`user_iduser`, `compra_idcompra`, `compra_livro_idlivro`),
  INDEX `fk_user_has_compra_compra1_idx` (`compra_idcompra` ASC, `compra_livro_idlivro` ASC) ,
  INDEX `fk_user_has_compra_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_user_has_compra_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariadb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_compra_compra1`
    FOREIGN KEY (`compra_idcompra` , `compra_livro_idlivro`)
    REFERENCES `livrariadb`.`compra` (`idcompra` , `livro_idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
