-- MySQL Script generated by MySQL Workbench
-- Sat May  4 13:55:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema livrariaDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema livrariaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livrariaDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `livrariaDB` ;

-- -----------------------------------------------------
-- Table `livrariaDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`user` (
  `iduser` INT ZEROFILL NOT NULL,
  `nome` VARCHAR(50) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `tipo` TINYINT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `longitude` DECIMAL NULL,
  `latitude` DECIMAL NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`, `Estado_idEstado`),
  INDEX `fk_Cidade_Estado_idx` (`Estado_idEstado` ASC) ,
  CONSTRAINT `fk_Cidade_Estado`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `livrariaDB`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `numero` INT NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `Cidade_idCidade`),
  INDEX `fk_Endereco_Cidade1_idx` (`Cidade_idCidade` ASC) ,
  CONSTRAINT `fk_Endereco_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `livrariaDB`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`imagens` (
  `idimagens` INT NOT NULL,
  `caminho` VARCHAR(45) NULL,
  PRIMARY KEY (`idimagens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`pessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`pessoaFisica` (
  `idpessoaFisica` VARCHAR(13) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `user_iduser` INT ZEROFILL NOT NULL,
  `sexo` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `imagens_idimagens` INT NOT NULL,
  PRIMARY KEY (`idpessoaFisica`, `Endereco_idEndereco`, `user_iduser`, `imagens_idimagens`),
  INDEX `fk_pessoaFisica_Endereco1_idx` (`Endereco_idEndereco` ASC) ,
  INDEX `fk_pessoaFisica_user1_idx` (`user_iduser` ASC) ,
  INDEX `fk_pessoaFisica_imagens1_idx` (`imagens_idimagens` ASC) ,
  CONSTRAINT `fk_pessoaFisica_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `livrariaDB`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaFisica_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariaDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaFisica_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `livrariaDB`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`post` (
  `idpost` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `conteudo` TEXT NULL,
  `descricao` VARCHAR(45) NULL,
  `categoria_idcategoria` INT NOT NULL,
  `datapostagem` TIMESTAMP NULL,
  PRIMARY KEY (`idpost`, `categoria_idcategoria`),
  INDEX `fk_post_categoria1_idx` (`categoria_idcategoria` ASC) ,
  CONSTRAINT `fk_post_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `livrariaDB`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`post_has_imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`post_has_imagens` (
  `post_idpost` INT NOT NULL,
  `imagens_idimagens` INT NOT NULL,
  PRIMARY KEY (`post_idpost`, `imagens_idimagens`),
  INDEX `fk_post_has_imagens_imagens1_idx` (`imagens_idimagens` ASC) ,
  INDEX `fk_post_has_imagens_post1_idx` (`post_idpost` ASC) ,
  CONSTRAINT `fk_post_has_imagens_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariaDB`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_imagens_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `livrariaDB`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`user_has_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`user_has_post` (
  `user_iduser` INT ZEROFILL NOT NULL,
  `post_idpost` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `post_idpost`),
  INDEX `fk_user_has_post_post1_idx` (`post_idpost` ASC) ,
  INDEX `fk_user_has_post_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_user_has_post_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariaDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_post_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariaDB`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`livro` (
  `idlivro` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  `descricao` VARCHAR(45) NULL,
  `ano` YEAR NULL,
  `peso` VARCHAR(45) NULL,
  PRIMARY KEY (`idlivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`user_has_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`user_has_livro` (
  `user_iduser` INT ZEROFILL NOT NULL,
  `livro_idlivro` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `livro_idlivro`),
  INDEX `fk_user_has_livro_livro1_idx` (`livro_idlivro` ASC) ,
  INDEX `fk_user_has_livro_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_user_has_livro_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariaDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_livro_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `livrariaDB`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NULL,
  `user_iduser` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idcomentarios`, `user_iduser`),
  INDEX `fk_comentarios_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_comentarios_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariaDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`post_has_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`post_has_comentarios` (
  `post_idpost` INT NOT NULL,
  `comentarios_idcomentarios` INT NOT NULL,
  `comentarios_user_iduser` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`post_idpost`, `comentarios_idcomentarios`, `comentarios_user_iduser`),
  INDEX `fk_post_has_comentarios_comentarios1_idx` (`comentarios_idcomentarios` ASC, `comentarios_user_iduser` ASC) ,
  INDEX `fk_post_has_comentarios_post1_idx` (`post_idpost` ASC) ,
  CONSTRAINT `fk_post_has_comentarios_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariaDB`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_comentarios_comentarios1`
    FOREIGN KEY (`comentarios_idcomentarios` , `comentarios_user_iduser`)
    REFERENCES `livrariaDB`.`comentarios` (`idcomentarios` , `user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`avaliacao` (
  `idavaliacao` INT NOT NULL,
  `quantidade` INT NULL,
  `user_iduser` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idavaliacao`, `user_iduser`),
  INDEX `fk_avaliacao_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_avaliacao_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `livrariaDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livrariaDB`.`post_has_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livrariaDB`.`post_has_avaliacao` (
  `post_idpost` INT NOT NULL,
  `avaliacao_idavaliacao` INT NOT NULL,
  `iduser` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`post_idpost`, `avaliacao_idavaliacao`, `iduser`),
  INDEX `fk_post_has_avaliacao_avaliacao1_idx` (`avaliacao_idavaliacao` ASC, `iduser` ASC) ,
  INDEX `fk_post_has_avaliacao_post1_idx` (`post_idpost` ASC) ,
  CONSTRAINT `fk_post_has_avaliacao_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `livrariaDB`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_avaliacao_avaliacao1`
    FOREIGN KEY (`avaliacao_idavaliacao` , `iduser`)
    REFERENCES `livrariaDB`.`avaliacao` (`idavaliacao` , `user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
